### ISSUE TITLE
Building PRoblem

### ISSUE THREAD

**Issue by TobiasOberle** [jmmorato/openddsharp_standard_helloworld#1]
Hey,
i checked out your this repository, following the instructions on:
https://www.openddsharp.com/articles/getting_started.html
but I can get it to build in VS2022 :(

When I getting to the point where i do:
dotnet build TestMessage.csproj --runtime win-x86

i get the Error:

SBuild version 17.3.0+92e077650 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  Add Visual C++ to the PATH...
C:\Users\to\.nuget\packages\openddsharp.standard.idlgenerator\0.8.22127.96\build\OpenDDSharp.Standard.IdlGenerator.targets(90,5): error MSB4181: The "AddPathVC" task returned false but did not log
 an error. [C:\_Sources\OpenDDsharpExample\TestMessage\TestMessage.csproj]

Build FAILED.

C:\Users\to\.nuget\packages\openddsharp.standard.idlgenerator\0.8.22127.96\build\OpenDDSharp.Standard.IdlGenerator.targets(90,5): error MSB4181: The "AddPathVC" task returned false but did not log
 an error. [C:\_Sources\OpenDDsharpExample\TestMessage\TestMessage.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.55

Do you have an Idea what goes wrong here?

**Comment by jmmorato** [comment]
Have you installed `Desktop development with C++` in your Visual Studio installer?

![image](https://user-images.githubusercontent.com/1584509/189521981-03bdce56-cb60-4e21-85cb-b48b5bb40a74.png)

It is not listed in the [Requirements](https://www.openddsharp.com/articles/getting_started.html#requirements) section (I will fix that) but C++ development tools are required for the compilation of the IDL projects

**Comment by TobiasOberle** [comment]
Hey Thanks for the fast answer.
I checked my VS2022 installation and "Desktop Development with C++" was checked still no clue whats causing this error... :(

**Comment by TobiasOberle** [comment]
I checked the example project from your repository again and stumbled on another error which i experienced already. 

![grafik](https://user-images.githubusercontent.com/64828686/189852007-819b8408-09a5-44b5-868d-665d08fbee17.png)

Maybe you can help me with this Error

**Comment by jmmorato** [comment]
You lost the `x`:
--runtime win-**x**64

**Comment by TobiasOberle** [comment]
that worked. Thanks a lot. Theres a mistake on the website saying its win-64
![grafik](https://user-images.githubusercontent.com/64828686/189886522-1e922135-c40d-4354-a5a3-823d034600da.png)

**Comment by jmmorato** [comment]
I will fix the documentation, thanks for reporting.

So, it work for you with `win-x64` but not for `win-x86`?

**Comment by jmmorato** [comment]
Closing by inactivity
