### ISSUE TITLE
My CS file cannot be generated. May I ask what is causing this

### ISSUE THREAD

**Issue by huajuhong** [jmmorato/openddsharp_standard_helloworld#11]
![image](https://github.com/jmmorato/openddsharp_standard_helloworld/assets/35752873/14361219-a000-4417-b6c1-8b1c0c42ce88)
My CS file cannot be generated. May I ask what is causing this.

**Comment by huajuhong** [comment]
![image](https://github.com/jmmorato/openddsharp_standard_helloworld/assets/35752873/3135f594-96b1-4369-a082-fdf02bc9d182)
Error reported during project build

**Comment by jmmorato** [comment]
Looks like you are trying to update from a previous version, aren't you?

If so, try to recreate the project files using the latest template for the new version.

**Comment by huajuhong** [comment]
@这个问题解决了，谢谢
我做了以下两点：
1. 需要Windows11
2. Visual Studio 2022安装需勾选“使用C++的桌面开发”

**Comment by jmmorato** [comment]
I close the issue then, thanks for sharing the solution.
